### ISSUE TITLE
SStables `ka` version support

### ISSUE THREAD

**Issue by geoah** [bharatendra/ctools#1]
@bharatendra, first of all I'd like to thank you for releasing this. It is an extremely useful library as datastax's sstables2json requires an function cassandra installation to do it's job.

Are there any plans or tips to make this work with `ka` format version?

```
// jb (2.0.1): switch from crc32 to adler32 for compression checksums
//             checksum the compressed data
// ka (2.1.0): new Statistics.db file format
//             index summaries can be downsampled and the sampling level is persisted
//             switch uncompressed checksums to adler32
//             tracks presense of legacy (local and remote) counter shards
```

The changes from `jb` don't seem very scary (at least from the doc) but a lack of better documentation makes it a bit hard to understand what's going on.

Thank you very much in advance.

**Comment by bharatendra** [comment]
Hello George,

Thank you for the feedback. I will incorporate the changes for version jb and ka in to the code. I will commit my changes this week.

**Comment by bharatendra** [comment]
Added support for parsing SSTable version 'ka'
