### ISSUE TITLE
column name is not identified in 2.1.12 ka version 

### ISSUE THREAD

**Issue by cw-deenbandhu** [bharatendra/ctools#4]
Hi i am getting special characters for column name my clustering key is compound key having datetime in it

**Comment by bharatendra** [comment]
Currently the code is printing column name as UTF8 string not interpreting the structure of column name. I will fix it soon

**Comment by bharatendra** [comment]
I modified sstable2json.py to take additional argument to specify composite type. For example if your column name is compounded using date and utf8 string please specify the argument as TimestampType,UTF8Type. 
This is a stand alone tool and it does't have access to the CQL table schema. So you need to pass the compound column types to the script. Currently it can decode only TimestampType and UTF8Type. I will add the support for other types soon.

**Comment by bharatendra** [comment]
Modified to use CQL type names timestamp, varchar and text. Please specify the argument as a comma separated list of CQL types. Currently only timestamp, varchar and text are supported.

**Comment by bharatendra** [comment]
Added additional types boolean,int,float,double and uuid in composite column name. Please specify the composite column name as a comma separated list of basic types (boolean,int,float,double,timestamp,utf8,uuid) to sstable2json.py
